// All FIFA-affiliated nations + territories — ~211 entries
// iso2 = ISO 3166-1 alpha-2 (used to generate flag emoji)
export const COUNTRIES = [
  { code: 'AFG', name: 'Afghanistan',              iso2: 'AF' },
  { code: 'ALB', name: 'Albania',                  iso2: 'AL' },
  { code: 'ALG', name: 'Algeria',                  iso2: 'DZ' },
  { code: 'AND', name: 'Andorra',                  iso2: 'AD' },
  { code: 'ANG', name: 'Angola',                   iso2: 'AO' },
  { code: 'ATG', name: 'Antigua & Barbuda',         iso2: 'AG' },
  { code: 'ARG', name: 'Argentina',                iso2: 'AR' },
  { code: 'ARM', name: 'Armenia',                  iso2: 'AM' },
  { code: 'AUS', name: 'Úc',                       iso2: 'AU' },
  { code: 'AUT', name: 'Áo',                       iso2: 'AT' },
  { code: 'AZE', name: 'Azerbaijan',               iso2: 'AZ' },
  { code: 'BHR', name: 'Bahrain',                  iso2: 'BH' },
  { code: 'BAN', name: 'Bangladesh',               iso2: 'BD' },
  { code: 'BRB', name: 'Barbados',                 iso2: 'BB' },
  { code: 'BLR', name: 'Belarus',                  iso2: 'BY' },
  { code: 'BEL', name: 'Bỉ',                      iso2: 'BE' },
  { code: 'BIZ', name: 'Belize',                   iso2: 'BZ' },
  { code: 'BEN', name: 'Benin',                    iso2: 'BJ' },
  { code: 'BHU', name: 'Bhutan',                   iso2: 'BT' },
  { code: 'BOL', name: 'Bolivia',                  iso2: 'BO' },
  { code: 'BIH', name: 'Bosnia & Herzegovina',     iso2: 'BA' },
  { code: 'BOT', name: 'Botswana',                 iso2: 'BW' },
  { code: 'BRA', name: 'Brazil',                   iso2: 'BR' },
  { code: 'VGB', name: 'British Virgin Islands',   iso2: 'VG' },
  { code: 'BRU', name: 'Brunei',                   iso2: 'BN' },
  { code: 'BUL', name: 'Bulgaria',                 iso2: 'BG' },
  { code: 'BFA', name: 'Burkina Faso',             iso2: 'BF' },
  { code: 'BDI', name: 'Burundi',                  iso2: 'BI' },
  { code: 'CAM', name: 'Campuchia',                iso2: 'KH' },
  { code: 'CAN', name: 'Canada',                   iso2: 'CA' },
  { code: 'CPV', name: 'Cape Verde',               iso2: 'CV' },
  { code: 'CAY', name: 'Cayman Islands',            iso2: 'KY' },
  { code: 'CAF', name: 'Central African Rep.',     iso2: 'CF' },
  { code: 'CHA', name: 'Chad',                     iso2: 'TD' },
  { code: 'CHI', name: 'Chile',                    iso2: 'CL' },
  { code: 'CHN', name: 'Trung Quốc',              iso2: 'CN' },
  { code: 'COL', name: 'Colombia',                 iso2: 'CO' },
  { code: 'COM', name: 'Comoros',                  iso2: 'KM' },
  { code: 'CGO', name: 'Congo',                    iso2: 'CG' },
  { code: 'COD', name: 'Congo DR',                 iso2: 'CD' },
  { code: 'CRC', name: 'Costa Rica',               iso2: 'CR' },
  { code: 'CIV', name: 'Côte d\'Ivoire',           iso2: 'CI' },
  { code: 'CRO', name: 'Croatia',                  iso2: 'HR' },
  { code: 'CUB', name: 'Cuba',                     iso2: 'CU' },
  { code: 'CUW', name: 'Curaçao',                  iso2: 'CW' },
  { code: 'CYP', name: 'Cyprus',                   iso2: 'CY' },
  { code: 'CZE', name: 'Czech',                    iso2: 'CZ' },
  { code: 'DEN', name: 'Đan Mạch',                iso2: 'DK' },
  { code: 'DJI', name: 'Djibouti',                 iso2: 'DJ' },
  { code: 'DOM', name: 'Dominican Republic',       iso2: 'DO' },
  { code: 'ECU', name: 'Ecuador',                  iso2: 'EC' },
  { code: 'EGY', name: 'Ai Cập',                  iso2: 'EG' },
  { code: 'SLV', name: 'El Salvador',              iso2: 'SV' },
  { code: 'ENG', name: 'Anh',                      iso2: 'GB' },
  { code: 'GNQ', name: 'Equatorial Guinea',        iso2: 'GQ' },
  { code: 'ERI', name: 'Eritrea',                  iso2: 'ER' },
  { code: 'EST', name: 'Estonia',                  iso2: 'EE' },
  { code: 'SWZ', name: 'Eswatini',                 iso2: 'SZ' },
  { code: 'ETH', name: 'Ethiopia',                 iso2: 'ET' },
  { code: 'FRO', name: 'Faroe Islands',            iso2: 'FO' },
  { code: 'FIJ', name: 'Fiji',                     iso2: 'FJ' },
  { code: 'FIN', name: 'Phần Lan',                iso2: 'FI' },
  { code: 'FRA', name: 'Pháp',                    iso2: 'FR' },
  { code: 'GAB', name: 'Gabon',                    iso2: 'GA' },
  { code: 'GAM', name: 'Gambia',                   iso2: 'GM' },
  { code: 'GEO', name: 'Georgia',                  iso2: 'GE' },
  { code: 'GER', name: 'Đức',                     iso2: 'DE' },
  { code: 'GHA', name: 'Ghana',                    iso2: 'GH' },
  { code: 'GIB', name: 'Gibraltar',                iso2: 'GI' },
  { code: 'GRE', name: 'Hy Lạp',                  iso2: 'GR' },
  { code: 'GRN', name: 'Grenada',                  iso2: 'GD' },
  { code: 'GLP', name: 'Guadeloupe',               iso2: 'GP' },
  { code: 'GUA', name: 'Guatemala',                iso2: 'GT' },
  { code: 'GUI', name: 'Guinea',                   iso2: 'GN' },
  { code: 'GNB', name: 'Guinea-Bissau',            iso2: 'GW' },
  { code: 'GUY', name: 'Guyana',                   iso2: 'GY' },
  { code: 'HAI', name: 'Haiti',                    iso2: 'HT' },
  { code: 'HKG', name: 'Hồng Kông',              iso2: 'HK' },
  { code: 'HON', name: 'Honduras',                 iso2: 'HN' },
  { code: 'HUN', name: 'Hungary',                  iso2: 'HU' },
  { code: 'ISL', name: 'Iceland',                  iso2: 'IS' },
  { code: 'IND', name: 'Ấn Độ',                  iso2: 'IN' },
  { code: 'IDN', name: 'Indonesia',                iso2: 'ID' },
  { code: 'IRN', name: 'Iran',                     iso2: 'IR' },
  { code: 'IRQ', name: 'Iraq',                     iso2: 'IQ' },
  { code: 'IRL', name: 'Ireland',                  iso2: 'IE' },
  { code: 'ISR', name: 'Israel',                   iso2: 'IL' },
  { code: 'ITA', name: 'Ý',                       iso2: 'IT' },
  { code: 'JAM', name: 'Jamaica',                  iso2: 'JM' },
  { code: 'JPN', name: 'Nhật Bản',               iso2: 'JP' },
  { code: 'JOR', name: 'Jordan',                   iso2: 'JO' },
  { code: 'KAZ', name: 'Kazakhstan',               iso2: 'KZ' },
  { code: 'KEN', name: 'Kenya',                    iso2: 'KE' },
  { code: 'PRK', name: 'Triều Tiên',              iso2: 'KP' },
  { code: 'KOR', name: 'Hàn Quốc',               iso2: 'KR' },
  { code: 'XKX', name: 'Kosovo',                   iso2: 'XK' },
  { code: 'KWT', name: 'Kuwait',                   iso2: 'KW' },
  { code: 'KGZ', name: 'Kyrgyzstan',               iso2: 'KG' },
  { code: 'LAO', name: 'Lào',                     iso2: 'LA' },
  { code: 'LVA', name: 'Latvia',                   iso2: 'LV' },
  { code: 'LBN', name: 'Lebanon',                  iso2: 'LB' },
  { code: 'LES', name: 'Lesotho',                  iso2: 'LS' },
  { code: 'LBR', name: 'Liberia',                  iso2: 'LR' },
  { code: 'LBA', name: 'Libya',                    iso2: 'LY' },
  { code: 'LIE', name: 'Liechtenstein',            iso2: 'LI' },
  { code: 'LTU', name: 'Lithuania',                iso2: 'LT' },
  { code: 'LUX', name: 'Luxembourg',               iso2: 'LU' },
  { code: 'MAC', name: 'Macau',                    iso2: 'MO' },
  { code: 'MAD', name: 'Madagascar',               iso2: 'MG' },
  { code: 'MWI', name: 'Malawi',                   iso2: 'MW' },
  { code: 'MAS', name: 'Malaysia',                 iso2: 'MY' },
  { code: 'MDV', name: 'Maldives',                 iso2: 'MV' },
  { code: 'MLI', name: 'Mali',                     iso2: 'ML' },
  { code: 'MLT', name: 'Malta',                    iso2: 'MT' },
  { code: 'MTQ', name: 'Martinique',               iso2: 'MQ' },
  { code: 'MTN', name: 'Mauritania',               iso2: 'MR' },
  { code: 'MRI', name: 'Mauritius',                iso2: 'MU' },
  { code: 'MEX', name: 'Mexico',                   iso2: 'MX' },
  { code: 'MDA', name: 'Moldova',                  iso2: 'MD' },
  { code: 'MNG', name: 'Mongolia',                 iso2: 'MN' },
  { code: 'MNE', name: 'Montenegro',               iso2: 'ME' },
  { code: 'MSR', name: 'Montserrat',               iso2: 'MS' },
  { code: 'MAR', name: 'Morocco',                  iso2: 'MA' },
  { code: 'MOZ', name: 'Mozambique',               iso2: 'MZ' },
  { code: 'MYA', name: 'Myanmar',                  iso2: 'MM' },
  { code: 'USA', name: 'Mỹ',                      iso2: 'US' },
  { code: 'NAM', name: 'Namibia',                  iso2: 'NA' },
  { code: 'NCL', name: 'New Caledonia',             iso2: 'NC' },
  { code: 'NZL', name: 'New Zealand',               iso2: 'NZ' },
  { code: 'NEP', name: 'Nepal',                    iso2: 'NP' },
  { code: 'NED', name: 'Hà Lan',                  iso2: 'NL' },
  { code: 'NCA', name: 'Nicaragua',                iso2: 'NI' },
  { code: 'NIG', name: 'Niger',                    iso2: 'NE' },
  { code: 'NGA', name: 'Nigeria',                  iso2: 'NG' },
  { code: 'NIR', name: 'Bắc Ireland',             iso2: 'GB' },
  { code: 'MKD', name: 'North Macedonia',          iso2: 'MK' },
  { code: 'NOR', name: 'Na Uy',                   iso2: 'NO' },
  { code: 'OMA', name: 'Oman',                     iso2: 'OM' },
  { code: 'PAK', name: 'Pakistan',                 iso2: 'PK' },
  { code: 'PLE', name: 'Palestine',                iso2: 'PS' },
  { code: 'PAN', name: 'Panama',                   iso2: 'PA' },
  { code: 'PNG', name: 'Papua New Guinea',          iso2: 'PG' },
  { code: 'PAR', name: 'Paraguay',                 iso2: 'PY' },
  { code: 'PER', name: 'Peru',                     iso2: 'PE' },
  { code: 'PHI', name: 'Philippines',              iso2: 'PH' },
  { code: 'POL', name: 'Ba Lan',                  iso2: 'PL' },
  { code: 'POR', name: 'Bồ Đào Nha',             iso2: 'PT' },
  { code: 'PUR', name: 'Puerto Rico',              iso2: 'PR' },
  { code: 'QAT', name: 'Qatar',                    iso2: 'QA' },
  { code: 'ROU', name: 'Romania',                  iso2: 'RO' },
  { code: 'RUS', name: 'Nga',                      iso2: 'RU' },
  { code: 'RWA', name: 'Rwanda',                   iso2: 'RW' },
  { code: 'SKN', name: 'Saint Kitts & Nevis',       iso2: 'KN' },
  { code: 'LCA', name: 'Saint Lucia',               iso2: 'LC' },
  { code: 'VIN', name: 'Saint Vincent',             iso2: 'VC' },
  { code: 'SAM', name: 'Samoa',                    iso2: 'WS' },
  { code: 'SMR', name: 'San Marino',               iso2: 'SM' },
  { code: 'STP', name: 'São Tomé & Príncipe',      iso2: 'ST' },
  { code: 'KSA', name: 'Ả Rập Xê Út',            iso2: 'SA' },
  { code: 'SCO', name: 'Scotland',                 iso2: 'GB' },
  { code: 'SEN', name: 'Senegal',                  iso2: 'SN' },
  { code: 'SRB', name: 'Serbia',                   iso2: 'RS' },
  { code: 'SEY', name: 'Seychelles',               iso2: 'SC' },
  { code: 'SLE', name: 'Sierra Leone',             iso2: 'SL' },
  { code: 'SGP', name: 'Singapore',                iso2: 'SG' },
  { code: 'SVK', name: 'Slovakia',                 iso2: 'SK' },
  { code: 'SVN', name: 'Slovenia',                 iso2: 'SI' },
  { code: 'SOL', name: 'Solomon Islands',           iso2: 'SB' },
  { code: 'SOM', name: 'Somalia',                  iso2: 'SO' },
  { code: 'RSA', name: 'Nam Phi',                  iso2: 'ZA' },
  { code: 'SSD', name: 'South Sudan',              iso2: 'SS' },
  { code: 'ESP', name: 'Tây Ban Nha',             iso2: 'ES' },
  { code: 'SRI', name: 'Sri Lanka',                iso2: 'LK' },
  { code: 'SDN', name: 'Sudan',                    iso2: 'SD' },
  { code: 'SUR', name: 'Suriname',                 iso2: 'SR' },
  { code: 'SUI', name: 'Thụy Sĩ',                iso2: 'CH' },
  { code: 'SWE', name: 'Thụy Điển',              iso2: 'SE' },
  { code: 'SYR', name: 'Syria',                    iso2: 'SY' },
  { code: 'TWN', name: 'Đài Loan',                iso2: 'TW' },
  { code: 'TJK', name: 'Tajikistan',               iso2: 'TJ' },
  { code: 'TAN', name: 'Tanzania',                 iso2: 'TZ' },
  { code: 'THA', name: 'Thái Lan',                iso2: 'TH' },
  { code: 'TLS', name: 'Timor-Leste',              iso2: 'TL' },
  { code: 'TOG', name: 'Togo',                     iso2: 'TG' },
  { code: 'TGA', name: 'Tonga',                    iso2: 'TO' },
  { code: 'TRI', name: 'Trinidad & Tobago',        iso2: 'TT' },
  { code: 'TUN', name: 'Tunisia',                  iso2: 'TN' },
  { code: 'TUR', name: 'Thổ Nhĩ Kỳ',             iso2: 'TR' },
  { code: 'TKM', name: 'Turkmenistan',             iso2: 'TM' },
  { code: 'TCA', name: 'Turks & Caicos Islands',   iso2: 'TC' },
  { code: 'UGA', name: 'Uganda',                   iso2: 'UG' },
  { code: 'UKR', name: 'Ukraine',                  iso2: 'UA' },
  { code: 'UAE', name: 'UAE',                      iso2: 'AE' },
  { code: 'URU', name: 'Uruguay',                  iso2: 'UY' },
  { code: 'UZB', name: 'Uzbekistan',               iso2: 'UZ' },
  { code: 'VAN', name: 'Vanuatu',                  iso2: 'VU' },
  { code: 'VEN', name: 'Venezuela',                iso2: 'VE' },
  { code: 'VIE', name: 'Việt Nam',                iso2: 'VN' },
  { code: 'WAL', name: 'Xứ Wales',                iso2: 'GB' },
  { code: 'TAH', name: 'Tahiti',                   iso2: 'PF' },
  { code: 'YEM', name: 'Yemen',                    iso2: 'YE' },
  { code: 'ZAM', name: 'Zambia',                   iso2: 'ZM' },
  { code: 'ZIM', name: 'Zimbabwe',                 iso2: 'ZW' },
];

export const FOOTBALL_POSITIONS = [
  { value: 'GK',  label: 'Thủ môn',              abbr: 'GK',  color: 'yellow' },
  { value: 'CB',  label: 'Trung vệ',              abbr: 'CB',  color: 'blue'   },
  { value: 'LB',  label: 'Hậu vệ trái',           abbr: 'LB',  color: 'blue'   },
  { value: 'RB',  label: 'Hậu vệ phải',           abbr: 'RB',  color: 'blue'   },
  { value: 'LWB', label: 'Hậu vệ tấn công trái',  abbr: 'LWB', color: 'blue'   },
  { value: 'RWB', label: 'Hậu vệ tấn công phải',  abbr: 'RWB', color: 'blue'   },
  { value: 'DM',  label: 'Tiền vệ phòng ngự',     abbr: 'DM',  color: 'green'  },
  { value: 'CM',  label: 'Tiền vệ trung tâm',     abbr: 'CM',  color: 'green'  },
  { value: 'AM',  label: 'Tiền vệ công',           abbr: 'AM',  color: 'green'  },
  { value: 'LM',  label: 'Tiền vệ trái',           abbr: 'LM',  color: 'green'  },
  { value: 'RM',  label: 'Tiền vệ phải',           abbr: 'RM',  color: 'green'  },
  { value: 'LW',  label: 'Cánh trái',              abbr: 'LW',  color: 'red'    },
  { value: 'RW',  label: 'Cánh phải',              abbr: 'RW',  color: 'red'    },
  { value: 'CF',  label: 'Tiền đạo cắm',           abbr: 'CF',  color: 'red'    },
  { value: 'ST',  label: 'Tiền đạo',               abbr: 'ST',  color: 'red'    },
  { value: 'SS',  label: 'Hộ công',                abbr: 'SS',  color: 'red'    },
  { value: 'F',   label: 'Tiền đạo chung',         abbr: 'F',   color: 'red'    },
  { value: 'M',   label: 'Tiền vệ chung',          abbr: 'M',   color: 'green'  },
  { value: 'D',   label: 'Hậu vệ chung',           abbr: 'D',   color: 'blue'   },
];
